"use client";

import Link from "next/link";
import { use, useEffect, useMemo, useRef, useState } from "react";

type Boleta = { id:string; numero:string; estado:string|null; nombre_cliente:string|null; telefono_cliente:string|null; email_cliente:string|null; valor_pagado:number|null; vendedor_nombre:string|null; canal:string|null };
type Props = { params: Promise<{ proyectoId: string }> };
type Editable = Omit<Boleta,"id"|"numero">;
const ESTADOS = ["Disponible","No disponible","Debe","Abonado","Pagado"];

export default function BaseDatosProyectoPage({ params }: Props) {
  const { proyectoId } = use(params);
  const fileRef = useRef<HTMLInputElement|null>(null);
  const [boletas,setBoletas]=useState<Boleta[]>([]), [proyectoNombre,setProyectoNombre]=useState("");
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [mensaje,setMensaje]=useState(""), [error,setError]=useState("");
  const [seleccionadas,setSeleccionadas]=useState<Set<string>>(new Set()), [ediciones,setEdiciones]=useState<Record<string,Editable>>({});
  const [busqueda,setBusqueda]=useState(""), [vendedor,setVendedor]=useState(""), [estado,setEstado]=useState(""), [telefono,setTelefono]=useState(""), [cliente,setCliente]=useState(""), [correo,setCorreo]=useState("");
  const [masivo,setMasivo]=useState<Record<string,string>>({});

  async function cargar(){try{setLoading(true);setError("");const res=await fetch(`/api/admin/proyectos/${proyectoId}/boletas`,{cache:"no-store",credentials:"include"});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.message||"No se pudo cargar la base de datos.");setBoletas(data.boletas||[]);setProyectoNombre(data.proyecto?.nombre||proyectoId);setEdiciones({});setSeleccionadas(new Set());}catch(e){setError(e instanceof Error?e.message:"Error desconocido.");}finally{setLoading(false);}}
  useEffect(()=>{void cargar();},[proyectoId]);

  const filtradas=useMemo(()=>{const nums=busqueda.split(/[\s,;]+/).map(v=>v.replace(/\D/g,"").padStart(4,"0")).filter(Boolean);const t=busqueda.trim().toLowerCase();return boletas.filter(b=>(!t||nums.includes(b.numero)||b.numero.includes(t))&&(!vendedor||(b.vendedor_nombre||"").toLowerCase().includes(vendedor.toLowerCase()))&&(!estado||b.estado===estado)&&(!telefono||(b.telefono_cliente||"").includes(telefono))&&(!cliente||(b.nombre_cliente||"").toLowerCase().includes(cliente.toLowerCase()))&&(!correo||(b.email_cliente||"").toLowerCase().includes(correo.toLowerCase())));},[boletas,busqueda,vendedor,estado,telefono,cliente,correo]);

  function valorFila(b:Boleta):Editable{return ediciones[b.id]||{estado:b.estado,nombre_cliente:b.nombre_cliente,telefono_cliente:b.telefono_cliente,email_cliente:b.email_cliente,valor_pagado:b.valor_pagado,vendedor_nombre:b.vendedor_nombre,canal:b.canal};}
  function editar(id:string,campo:keyof Editable,valor:string|number|null){const b=boletas.find(x=>x.id===id);if(!b)return;setEdiciones(p=>({...p,[id]:{...valorFila(b),[campo]:valor}}));}
  async function actualizar(ids:string[],cambios:Record<string,unknown>){setSaving(true);setError("");setMensaje("");try{const res=await fetch(`/api/admin/proyectos/${proyectoId}/boletas`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids,cambios})});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.message||"No se pudo actualizar.");setMensaje(`${data.actualizadas||0} registro(s) actualizado(s).`);await cargar();}catch(e){setError(e instanceof Error?e.message:"Error desconocido.");}finally{setSaving(false);}}
  function aplicarMasivo(){const cambios=Object.fromEntries(Object.entries(masivo).filter(([,v])=>v!==""));void actualizar(Array.from(seleccionadas),cambios);}

  async function cargarCsv(file:File){setSaving(true);setError("");setMensaje("Procesando archivo...");try{const texto=await file.text();const lineas=texto.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const headers=lineas[0].split(",").map(h=>h.trim().toLowerCase().replace(/\s+/g,"_"));const items=lineas.slice(1).map(linea=>{const c=linea.split(",");const get=(...ns:string[])=>{const i=ns.map(n=>headers.indexOf(n)).find(i=>i>=0);return i===undefined?"":(c[i]||"").trim();};return{numero:get("numero","boleta","consecutivo"),estado:get("estado"),nombre:get("nombre","nombre_cliente"),telefono:get("telefono","telefono_cliente"),email:get("email","correo"),valor_pagado:get("valor_pagado","valor"),vendedor:get("vendedor","vendedor_nombre"),canal:get("canal")};}).filter(i=>i.numero);const res=await fetch(`/api/proyectos/${proyectoId}/actualizar-base-datos`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items})});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.message||"No se pudo cargar el archivo.");setMensaje(`Carga manual completada. Actualizadas: ${data.actualizadas||0}. Omitidas: ${data.omitidas||0}.`);await cargar();}catch(e){setError(e instanceof Error?e.message:"Error cargando CSV.");}finally{setSaving(false);if(fileRef.current)fileRef.current.value="";}}

  const campos=[["estado","Estado"],["nombre_cliente","Nombre cliente"],["telefono_cliente","Teléfono"],["email_cliente","Email"],["valor_pagado","Valor pagado"],["vendedor_nombre","Vendedor"],["canal","Canal"]] as const;

  return <main className="min-h-screen bg-[#F2EDE4] p-4 text-[#1A1A1A]"><section className="mx-auto max-w-[1600px]">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm uppercase tracking-[3px] text-[#7A7066]">Base de datos</p><h1 className="mt-2 text-3xl font-bold">{proyectoNombre}</h1></div><div className="flex gap-2"><Link href="/admin" className="rounded-xl border border-[#1A1A1A] bg-white px-4 py-3 font-semibold">Volver</Link><button onClick={()=>fileRef.current?.click()} className="rounded-xl bg-[#E8620A] px-4 py-3 font-semibold text-white">Cargar base de datos manual</button><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>e.target.files?.[0]&&void cargarCsv(e.target.files[0])}/></div></div>
    {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{mensaje&&<div className="mb-4 rounded-xl border border-green-200 bg-green-50 p-4 text-green-700">{mensaje}</div>}
    <div className="mb-5 grid gap-3 rounded-2xl bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Número o lista de números" className="rounded-xl border p-3"/><input value={vendedor} onChange={e=>setVendedor(e.target.value)} placeholder="Vendedor" className="rounded-xl border p-3"/><select value={estado} onChange={e=>setEstado(e.target.value)} className="rounded-xl border p-3"><option value="">Todos los estados</option>{ESTADOS.map(x=><option key={x}>{x}</option>)}</select><input value={telefono} onChange={e=>setTelefono(e.target.value)} placeholder="Teléfono" className="rounded-xl border p-3"/><input value={cliente} onChange={e=>setCliente(e.target.value)} placeholder="Nombre cliente" className="rounded-xl border p-3"/><input value={correo} onChange={e=>setCorreo(e.target.value)} placeholder="Correo" className="rounded-xl border p-3"/></div>
    {seleccionadas.size>0&&<div className="mb-5 rounded-2xl border border-[#E8620A] bg-white p-4"><p className="mb-3 font-semibold">{seleccionadas.size} seleccionada(s). Completa solo los campos que deseas cambiar.</p><div className="grid gap-3 md:grid-cols-4">{campos.map(([c,l])=>c==="estado"?<select key={c} value={masivo[c]||""} onChange={e=>setMasivo({...masivo,[c]:e.target.value})} className="rounded-xl border p-3"><option value="">{l}</option>{ESTADOS.map(x=><option key={x}>{x}</option>)}</select>:<input key={c} type={c==="valor_pagado"?"number":"text"} value={masivo[c]||""} onChange={e=>setMasivo({...masivo,[c]:e.target.value})} placeholder={l} className="rounded-xl border p-3"/>)}</div><button disabled={saving} onClick={aplicarMasivo} className="mt-3 rounded-xl bg-[#1A1A1A] px-5 py-3 font-semibold text-white disabled:opacity-50">Actualizar seleccionadas</button></div>}
    <div className="overflow-auto rounded-2xl bg-white shadow-sm">{loading?<p className="p-8 text-center">Cargando...</p>:<table className="min-w-[1500px] w-full text-sm"><thead className="sticky top-0 bg-[#1A1A1A] text-white"><tr><th className="p-3"><input type="checkbox" checked={filtradas.length>0&&filtradas.every(b=>seleccionadas.has(b.id))} onChange={e=>setSeleccionadas(e.target.checked?new Set(filtradas.map(b=>b.id)):new Set())}/></th><th className="p-3 text-left">Número</th>{campos.map(([,l])=><th key={l} className="p-3 text-left">{l}</th>)}<th className="p-3">Acción</th></tr></thead><tbody>{filtradas.map(b=>{const v=valorFila(b);return <tr key={b.id} className="border-b align-top"><td className="p-2"><input type="checkbox" checked={seleccionadas.has(b.id)} onChange={e=>setSeleccionadas(p=>{const n=new Set(p);e.target.checked?n.add(b.id):n.delete(b.id);return n;})}/></td><td className="p-2 font-semibold">{b.numero}</td><td className="p-2"><select value={v.estado||""} onChange={e=>editar(b.id,"estado",e.target.value)} className="w-40 rounded border p-2">{ESTADOS.map(x=><option key={x}>{x}</option>)}</select></td><td className="p-2"><input value={v.nombre_cliente||""} onChange={e=>editar(b.id,"nombre_cliente",e.target.value)} className="w-44 rounded border p-2"/></td><td className="p-2"><input value={v.telefono_cliente||""} onChange={e=>editar(b.id,"telefono_cliente",e.target.value)} className="w-36 rounded border p-2"/></td><td className="p-2"><input value={v.email_cliente||""} onChange={e=>editar(b.id,"email_cliente",e.target.value)} className="w-52 rounded border p-2"/></td><td className="p-2"><input type="number" value={v.valor_pagado??0} onChange={e=>editar(b.id,"valor_pagado",Number(e.target.value))} className="w-32 rounded border p-2"/></td><td className="p-2"><input value={v.vendedor_nombre||""} onChange={e=>editar(b.id,"vendedor_nombre",e.target.value)} className="w-44 rounded border p-2"/></td><td className="p-2"><input value={v.canal||""} onChange={e=>editar(b.id,"canal",e.target.value)} className="w-36 rounded border p-2"/></td><td className="p-2"><button disabled={!ediciones[b.id]||saving} onClick={()=>void actualizar([b.id],ediciones[b.id])} className="rounded-lg bg-[#E8620A] px-3 py-2 font-semibold text-white disabled:opacity-40">Actualizar</button></td></tr>})}</tbody></table>}</div><p className="mt-3 text-sm text-[#6F665C]">Mostrando {filtradas.length} de {boletas.length} registros.</p>
  </section></main>;
}
